name: 🚀➕ Enhancement Request
description: Suggest an enhancement for this project. Improve an existing feature
title: "[🚀➕]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement report!

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: checkboxes
    id: openissue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Is your enhancement request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your proposed solution
      description: A clear and concise description of the proposed solution.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your solution.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the proposed solution here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Contributor
      description: Mention contributor or stakeholder.
    validations:
      required: false
